#
#
# 最小レート。
#   読込時に最小レート以下の棋譜は読込まない。
#   ただし、0の場合はレートのチェックをしない。
app.rate.min = 2000
# app.rate.min = 0
#
# 大量の棋譜ののあるzipファイル名。Noneならskipする
app.load.target =  E:/assets/book.zip,E:/assets/target/2021.zip,E:/assets/target/2022.zip,E:/assets/target/2023.zip,E:/assets/target/2024.zip,E:/assets/target/2025.zip
# app.load.target = None
#
# ボーダーライン// これより小さい値は定跡として持たない
app.border = 4
#
# チャネルの最大数
app.channel.max = 16


# 全テーブルをDB化したもの
app.db.all = E:/assets/mytable_all.db

# 全テーブルをDB化したもの
app.db.total = E:/assets/mytable_total.db

# 棋譜をボーダーで縮小したもの
app.db.small = E:/assets/mytable_small.db

# 棋譜をボーダーで縮小したものを学習させたもの
app.db.eval = E:/assets/mytable_eval.db

# ダメな手を生成する
app.db.bad = E:/assets/mytable_bad.db

# 評価用
app.db.estimate = E:/assets/mytable_estimate.db

# 棋譜を小さくしたものの残り物
app.db.remain = E:/assets/mytable_remain.db

# dataset の全体
app.dataset.all = E:/assets/dataset_all

#
url.policy = https://github.com/Tand0/ShogiO
#
url.report = https://github.com/Tand0/ShogiO/issues
#
